### ISSUE TITLE
empty triple

### ISSUE THREAD

**Issue by WeiShi-9** [vj1494/PipelineIE#2]
```
                     Sentences Triplet
1  the park does not have beds      []
```
I am using pipelineie as the example in the readme file. However, I got many sentences with empty triple extraction, how can I fix it?

**Comment by vj1494** [comment]
The pipeline uses Subject Verb Object Rule for extracting triplets. In the case it does not find relationships as per this rule, it will return empty triplets. You will need to write additional rules to handle the cases where the sentence is not of such a form.
